const endpoints = {
  admin: {
    adminlogin: 'api/auth/admin',
    queryAdmin: 'api/admin/me',
    uploadAdminImg: 'api/admin/upload',
    deleteAdminImg: 'api/admin/image/',
    adminImg: 'api/admin/image/',
    getEmergencies: 'api/emergency',
    deleteEmergency: 'api/emergency/',
    readEmergency: 'api/emergency/notice/',
  },
  category: {
    categoryNumber: 'api/category/checkup',
    uploadCategoryIcon: 'api/category/checkup/upload',
    addCategoryDetails: 'api/category/checkup',
    deleteCategoryDetails: 'api/category/checkup/',
    deleteCategoryImage: 'api/category/checkup/image/',
    categoryImg: 'api/category/checkup/image/',
    queryCategoryData: 'api/category/checkups',
    querySingleCategoryData: 'api/category/checkup/',
    editCategoryDetails: 'api/category/checkup/',
    addDisease: 'api/category/checkup/',
    deleteDiease: 'api/category/checkup',
    addAvailableDoc: 'api/category/checkup/',
    dltAvailableDoc: 'api/category/checkup/',
  },
  doctors: {
    getDoctorNumber: 'api/category/doctors/length',
    queryDoctor: 'api/category/doctors',
    querySingleDoctor: 'api/category/doctor/',
    uploadDoctorImg: 'api/category/doctor/upload',
    addDoctorDetails: 'api/category/doctor',
    editDoctorDetails: 'api/category/doctor/',
    deleteDoctor: 'api/category/doctor/',
    doctorImg: 'api/category/doctor/image/',
    available: 'api/category/doctor/',
    dltAvailable: 'api/category/doctor/'
  },
  rooms: {
    addRoomDetails: 'api/category/room',
    addRoomImage: 'api/category/room/upload',
    getRoomNumber: 'api/category/room/length',
    queryRoomData: 'api/category/rooms',
    querySingleRoom: 'api/category/room/',
    roomImg: 'api/category/room/image/',
    editRoomDetails: 'api/category/room/',
    deleteRoom: 'api/category/room/',
    deleteBooking: 'api/user/book/room/',
  },
  user: {
    getUserNumber: 'api/user/users/length',
    getUsersData: 'api/user/users',
    userImg: 'api/user/image/',
    getSingleUser: 'api/user/',
    uploadUserReport: 'api/user/upload/report/',
    getUserReport: 'api/user/image/report/',
    deleteUserReport: 'api/user/image/report/',
  },
};

export { endpoints };
