export const GET_ADMIN_DATA = 'GET_ADMIN_DATA';
export const GET_ADMIN_DATA_FAILED = 'GET_ADMIN_DATA_FAILED';
export const UPLOAD_ADMIN_PROFILE_PICTURE = 'UPLOAD_ADMIN_PROFILE_PICTURE';
export const UPLOAD_ADMIN_PROFILE_PICTURE_FAILED =
  'UPLOAD_ADMIN_PROFILE_PICTURE_FAILED';
export const DELETE_ADMIN_PROFILE_PICTURE = 'DELETE_ADMIN_PROFILE_PICTURE';
export const DELETE_ADMIN_PROFILE_PICTURE_FAILED =
  'DELETE_ADMIN_PROFILE_PICTURE_FAILED';
export const ADMIN_LOGIN = 'ADMIN_LOGIN';
export const ADMIN_LOGIN_FAILED = 'ADMIN_LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const GET_EMERGENCIES = 'GET_EMERGENCIES';
export const DELETE_EMERGENCY = 'DELETE_EMERGENCY';
export const READ_NOTICE = 'READ_NOTICE';
export const DLT_NOTICE = 'DLT_NOTICE';

// room details actions
export const ADD_ROOM_DETAILS = 'ADD_ROOM_DETAILS';
export const ADD_ROOM_DETAILS_FAILED = 'ADD_ROOM_DETAILS_FAILED';
export const UPLOAD_ROOM_IMAGE = 'ADD_ROOM_IMAGE';
export const UPLOAD_ROOM_IMAGE_FAILED = 'ADD_ROOM_IMAGE_FAILED';
export const EDIT_ROOM_DETAILS = 'EDIT_ROOM_DETAILS';
export const EDIT_ROOM_DETAILS_FAILED = 'EDIT_ROOM_DETAILS_FAILED';
export const DLT_ROOM_BOOKING = 'DLT_ROOM_BOOKING';

// doctor details actions
export const ADD_DOCTOR_DETAILS = 'ADD_DOCTOR_DETAILS';
export const ADD_DOCTOR_DETAILS_FAILED = 'ADD_DOCTOR_DETAILS_FAILED';
export const UPLOAD_DOCTOR_IMAGE = 'UPLOAD_DOCTOR_IMAGE';
export const UPLOAD_DOCTOR_IMAGE_FAILED = 'UPLOAD_DOCTOR_IMAGE_FAILED';
export const EDIT_DOCTOR_DETAILS = 'EDIT_DOCTOR_DETAILS';
export const EDIT_DOCTOR_DETAILS_FAILED = 'EDIT_DOCTOR_DETAILS_FAILED';
export const DLT_BOOKED_DATE = 'DLT_BOOKED_DATE';
export const ADD_AVAILABLE_DATE = 'ADD_AVAILABLE_DATE';
export const DLT_AVAILABLE_DATE = 'DLT_AVAILABLE_DATE';
export const ADD_AVAILABLE_TIME = 'ADD_AVAILABLE_TIME';
export const DLT_AVAILABLE_TIME = 'DLT_AVAILABLE_TIME';

// checkup category details actions
export const ADD_CATEGORY_DETAILS = 'ADD_CATEGORY_DETAILS';
export const ADD_CATEGORY_DETAILS_FAILED = 'ADD_CATEGORY_DETAILS_FAILED';
export const UPLOAD_CATEGORY_IMAGE = 'UPLOAD_CATEGORY_IMAGE';
export const UPLOAD_CATEGORY_IMAGE_FAILED = 'UPLOAD_CATEGORY_IMAGE_FAILED';
export const EDIT_CATEGORY_DETAILS = 'EDIT_CATEGORY_DETAILS';
export const EDIT_CATEGORY_DETAILS_FAILED = 'EDIT_DOCTOR_DCATEGORY_FAILED';
export const ADD_DISEASE_DETAILS = 'ADD_DISEASE_DETAILS';
export const ADD_DISEASE_DETAILS_FAILED = 'ADD_DISEASE_DETAILS_FAILED';
export const DLT_DIESEASE = 'DLT_DISEASE';
export const ADD_AVAILABLE_DOC = 'ADD_AVAILABLE_DOC';
export const ADD_AVAILABLE_DOC_FAILED = ' ADD_AVAILABLE_DOC_FAILED';
export const DELETE_AVAILABLE_DOC = 'DELETE_AVAILABLE_DOC';

// get the dashboard data only
export const GET_ROOM_NUMBER = 'GET_ROOM_NUMBER';
export const GET_ROOM_NUMBER_FAILED = 'GET_ROOM_NUMBER_FAILED';
export const GET_DOCTOR_NUMBER = 'GET_DOCTOR_NUMBER';
export const GET_DOCTOR_NUMBER_FAILED = 'GET_DOCTOR_NUMBER_FAILED';
export const GET_USERS_NUMBER = 'GET_USERS_NUMBER';
export const GET_USERS_NUMBER_FAILED = 'GET_USERS_NUMBER_FAILED';
export const GET_CATEGORIES_NUMBER = 'GET_CATEGORIES_NUMBER';
export const GET_CATEGORIES_NUMBER_FAILED = 'GET_CATEGORIES_NUMBER_FAILED';

//query data
export const GET_DOCTORS = 'GET_DOCTORS';
export const GET_DOCTORS_FAILED = 'GET_DOCTORS_FAILED';
export const GET_ROOMS = 'GET_ROOMS';
export const GET_ROOMS_FAILED = 'GET_ROOMS_FAILED';
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_FAILED = 'GET_CATEGORY_FAILED';
export const GET_SINGLE_CATEGORY = 'GET_SINGLE_CATEGORY';
export const GET_SINGLE_CATEGORY_FAILED = 'GET_SINGLE_CATEGORY_FAILED';
export const GET_SINGLE_DOCTOR = 'GET_SINGLE_DOCTOR';
export const GET_SINGLE_DOCTOR_FAILED = 'GET_SINGLE_DOCTOR_FAILED';
export const GET_SINGLE_ROOM = 'GET_SINGLE_ROOM';
export const GET_SINGLE_ROOM_FAILED = 'GET_SINGLE_ROOM_FAILED';

// delete actions
export const DELETE_DOCTOR_FAILED = 'DELETE_DOCTOR_FAILED';
export const DELETE_ROOM_FAILED = 'DELETE_ROOM_FAILED';
export const DELETE_CATEGORY_FAILED = 'DELETE_CATEGORY_FAILED';
export const DELETE_DISEASE_FAILED = 'DELETE_DISEASE_FAILED';

// user actions only
export const GET_USERS = 'GET_USERS';
export const GET_SINLGE_USER = 'GET_SINGLE_USER';
export const UPLOAD_USER_REPORT = 'UPLOAD_USER_REPORT';

//helps in global state management